module.exports = {
    first: [
        "mus",
        "brandt",
        "o",
        "dor",
        "ardo",
        "angelo",
        "aggio",
        "deo",
        "-Michel",
        " El",
        " de",
    ],
    last: [
        "Rothko",
        "Johns",
        "Picasso",
        "Monet",
        "Manet",
        "Picasso",
        "van Gogh",
        "da Vinci",
        "Vermeer",
    ],
};
